server:
  port: 8080
spring:
  application:
    name: "Semana1"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: "${POSTGRES_HOST:postgres-hu1}"
    port: "${POSTGRES_PORT:5432}"
    database: "${POSTGRES_DB:perylothdb}"
    schema: "public"
    username: "${POSTGRES_USER:user}"
    password: "${POSTGRES_PASSWORD:password}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
auth:
  number-login-max:5
